ES6 Awesome books
EyasuTeshome/ES6-Awesome-Books pull request #1
Opened 2022-07-11 13:56 UTC by EyasuTeshome

completed the project using ES6 syntax and by creating four modules to add, remove and save books into local storage and one additional module from luxon to add time and date to the website.

2022-07-11 15:29 UTC, omarsalem7 requested changes
Hi @EyasuTeshome 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-11 15:29 UTC, omarsalem7 commented on modules/empty.js
> +console.log('hello', appName);
- [ ] It will be better if you remove this file or add it in the '.gitignore' file to make your project contain all important files.

2022-07-11 15:29 UTC, omarsalem7 commented on modules/remove.mjs
> +};
- [ ] kindly update the data in local storage after removing it because when refresh the removed data render again.

2022-07-12 12:46 UTC, zhadier approved these changes
## Hi @EyasuTeshome  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

### Keep Rocking!👏👏👏
## Optional
<hr/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 13:03 UTC, merged